// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1kYszxinVjf6lTLHeJUWbI5REHeodpVE',
    appId: '1:208337442046:web:318ded9127692bc4da41af',
    messagingSenderId: '208337442046',
    projectId: 'abmdistribution-57f25',
    authDomain: 'abmdistribution-57f25.firebaseapp.com',
    storageBucket: 'abmdistribution-57f25.appspot.com',
    measurementId: 'G-LZ8DJ9M56X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrEaBKmo49wNwZniVgHg1NK42zYg7C00',
    appId: '1:208337442046:android:05af88e503af819ada41af',
    messagingSenderId: '208337442046',
    projectId: 'abmdistribution-57f25',
    storageBucket: 'abmdistribution-57f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZrp7fJ6YlOnZfkN2P9uMNgF_4-JXMt8E',
    appId: '1:208337442046:ios:05a3d9c0ec8e8355da41af',
    messagingSenderId: '208337442046',
    projectId: 'abmdistribution-57f25',
    storageBucket: 'abmdistribution-57f25.appspot.com',
    iosBundleId: 'com.example.Abm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZrp7fJ6YlOnZfkN2P9uMNgF_4-JXMt8E',
    appId: '1:208337442046:ios:05a3d9c0ec8e8355da41af',
    messagingSenderId: '208337442046',
    projectId: 'abmdistribution-57f25',
    storageBucket: 'abmdistribution-57f25.appspot.com',
    iosBundleId: 'com.example.Abm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1kYszxinVjf6lTLHeJUWbI5REHeodpVE',
    appId: '1:208337442046:web:b81515419d21abf1da41af',
    messagingSenderId: '208337442046',
    projectId: 'abmdistribution-57f25',
    authDomain: 'abmdistribution-57f25.firebaseapp.com',
    storageBucket: 'abmdistribution-57f25.appspot.com',
    measurementId: 'G-LWQDJ0BEXB',
  );
}
